export interface SeedFoodItem {
  name: string;
  category: string;
  unit: string;
}

// Seed data for the food database: common Swedish grocery items with a
// sensible default unit. The seed script is idempotent (matches on lowercase
// name), so adding entries here and re-running is safe.
export const FOOD_ITEMS: SeedFoodItem[] = [
  // ── Frukt & Grönt ──
  { name: "Bananer", category: "Frukt & Grönt", unit: "st" },
  { name: "Äpplen", category: "Frukt & Grönt", unit: "st" },
  { name: "Apelsiner", category: "Frukt & Grönt", unit: "st" },
  { name: "Citron", category: "Frukt & Grönt", unit: "st" },
  { name: "Lime", category: "Frukt & Grönt", unit: "st" },
  { name: "Päron", category: "Frukt & Grönt", unit: "st" },
  { name: "Vindruvor", category: "Frukt & Grönt", unit: "förp" },
  { name: "Jordgubbar", category: "Frukt & Grönt", unit: "förp" },
  { name: "Blåbär", category: "Frukt & Grönt", unit: "förp" },
  { name: "Hallon", category: "Frukt & Grönt", unit: "förp" },
  { name: "Avokado", category: "Frukt & Grönt", unit: "st" },
  { name: "Tomater", category: "Frukt & Grönt", unit: "kg" },
  { name: "Körsbärstomater", category: "Frukt & Grönt", unit: "förp" },
  { name: "Gurka", category: "Frukt & Grönt", unit: "st" },
  { name: "Paprika", category: "Frukt & Grönt", unit: "st" },
  { name: "Isbergssallad", category: "Frukt & Grönt", unit: "st" },
  { name: "Ruccola", category: "Frukt & Grönt", unit: "förp" },
  { name: "Babyspenat", category: "Frukt & Grönt", unit: "förp" },
  { name: "Morötter", category: "Frukt & Grönt", unit: "kg" },
  { name: "Potatis", category: "Frukt & Grönt", unit: "kg" },
  { name: "Sötpotatis", category: "Frukt & Grönt", unit: "kg" },
  { name: "Gul lök", category: "Frukt & Grönt", unit: "kg" },
  { name: "Rödlök", category: "Frukt & Grönt", unit: "kg" },
  { name: "Vitlök", category: "Frukt & Grönt", unit: "st" },
  { name: "Purjolök", category: "Frukt & Grönt", unit: "st" },
  { name: "Broccoli", category: "Frukt & Grönt", unit: "st" },
  { name: "Blomkål", category: "Frukt & Grönt", unit: "st" },
  { name: "Zucchini", category: "Frukt & Grönt", unit: "st" },
  { name: "Champinjoner", category: "Frukt & Grönt", unit: "förp" },
  { name: "Ingefära", category: "Frukt & Grönt", unit: "st" },
  { name: "Färsk koriander", category: "Frukt & Grönt", unit: "st" },
  { name: "Färsk basilika", category: "Frukt & Grönt", unit: "st" },
  { name: "Dill", category: "Frukt & Grönt", unit: "st" },
  { name: "Persilja", category: "Frukt & Grönt", unit: "st" },

  // ── Bröd & Bageri ──
  { name: "Formfranska", category: "Bröd & Bageri", unit: "st" },
  { name: "Fullkornsbröd", category: "Bröd & Bageri", unit: "st" },
  { name: "Baguette", category: "Bröd & Bageri", unit: "st" },
  { name: "Knäckebröd", category: "Bröd & Bageri", unit: "förp" },
  { name: "Tortillabröd", category: "Bröd & Bageri", unit: "förp" },
  { name: "Pitabröd", category: "Bröd & Bageri", unit: "förp" },
  { name: "Hamburgerbröd", category: "Bröd & Bageri", unit: "förp" },
  { name: "Korvbröd", category: "Bröd & Bageri", unit: "förp" },
  { name: "Kanelbullar", category: "Bröd & Bageri", unit: "förp" },
  { name: "Skorpor", category: "Bröd & Bageri", unit: "förp" },

  // ── Mejeri & Ägg ──
  { name: "Mellanmjölk", category: "Mejeri & Ägg", unit: "l" },
  { name: "Lättmjölk", category: "Mejeri & Ägg", unit: "l" },
  { name: "Standardmjölk", category: "Mejeri & Ägg", unit: "l" },
  { name: "Havredryck", category: "Mejeri & Ägg", unit: "l" },
  { name: "Filmjölk", category: "Mejeri & Ägg", unit: "l" },
  { name: "Naturell yoghurt", category: "Mejeri & Ägg", unit: "l" },
  { name: "Vaniljyoghurt", category: "Mejeri & Ägg", unit: "l" },
  { name: "Vispgrädde", category: "Mejeri & Ägg", unit: "förp" },
  { name: "Matlagningsgrädde", category: "Mejeri & Ägg", unit: "förp" },
  { name: "Crème fraiche", category: "Mejeri & Ägg", unit: "förp" },
  { name: "Gräddfil", category: "Mejeri & Ägg", unit: "förp" },
  { name: "Smör", category: "Mejeri & Ägg", unit: "förp" },
  { name: "Bregott", category: "Mejeri & Ägg", unit: "förp" },
  { name: "Ägg 12-pack", category: "Mejeri & Ägg", unit: "förp" },
  { name: "Prästost", category: "Mejeri & Ägg", unit: "st" },
  { name: "Hushållsost", category: "Mejeri & Ägg", unit: "st" },
  { name: "Mozzarella", category: "Mejeri & Ägg", unit: "förp" },
  { name: "Fetaost", category: "Mejeri & Ägg", unit: "förp" },
  { name: "Parmesan", category: "Mejeri & Ägg", unit: "st" },
  { name: "Kvarg", category: "Mejeri & Ägg", unit: "förp" },
  { name: "Keso", category: "Mejeri & Ägg", unit: "förp" },

  // ── Kött & Fågel ──
  { name: "Kycklingfilé", category: "Kött & Fågel", unit: "kg" },
  { name: "Kycklinglårfilé", category: "Kött & Fågel", unit: "kg" },
  { name: "Hel kyckling", category: "Kött & Fågel", unit: "st" },
  { name: "Nötfärs", category: "Kött & Fågel", unit: "kg" },
  { name: "Blandfärs", category: "Kött & Fågel", unit: "kg" },
  { name: "Fläskfilé", category: "Kött & Fågel", unit: "kg" },
  { name: "Fläskkotletter", category: "Kött & Fågel", unit: "kg" },
  { name: "Falukorv", category: "Kött & Fågel", unit: "st" },
  { name: "Prinskorv", category: "Kött & Fågel", unit: "förp" },
  { name: "Grillkorv", category: "Kött & Fågel", unit: "förp" },
  { name: "Bacon", category: "Kött & Fågel", unit: "förp" },
  { name: "Skinkpålägg", category: "Kött & Fågel", unit: "förp" },
  { name: "Salami", category: "Kött & Fågel", unit: "förp" },
  { name: "Leverpastej", category: "Kött & Fågel", unit: "st" },

  // ── Fisk & Skaldjur ──
  { name: "Laxfilé", category: "Fisk & Skaldjur", unit: "kg" },
  { name: "Torskfilé", category: "Fisk & Skaldjur", unit: "kg" },
  { name: "Räkor", category: "Fisk & Skaldjur", unit: "kg" },
  { name: "Gravad lax", category: "Fisk & Skaldjur", unit: "förp" },
  { name: "Sill", category: "Fisk & Skaldjur", unit: "förp" },
  { name: "Kaviar", category: "Fisk & Skaldjur", unit: "st" },
  { name: "Tonfisk på burk", category: "Fisk & Skaldjur", unit: "st" },
  { name: "Makrill i tomatsås", category: "Fisk & Skaldjur", unit: "st" },

  // ── Skafferi ──
  { name: "Spaghetti", category: "Skafferi", unit: "förp" },
  { name: "Penne", category: "Skafferi", unit: "förp" },
  { name: "Makaroner", category: "Skafferi", unit: "förp" },
  { name: "Lasagneplattor", category: "Skafferi", unit: "förp" },
  { name: "Ris", category: "Skafferi", unit: "förp" },
  { name: "Bulgur", category: "Skafferi", unit: "förp" },
  { name: "Couscous", category: "Skafferi", unit: "förp" },
  { name: "Quinoa", category: "Skafferi", unit: "förp" },
  { name: "Havregryn", category: "Skafferi", unit: "förp" },
  { name: "Müsli", category: "Skafferi", unit: "förp" },
  { name: "Cornflakes", category: "Skafferi", unit: "förp" },
  { name: "Vetemjöl", category: "Skafferi", unit: "kg" },
  { name: "Strösocker", category: "Skafferi", unit: "kg" },
  { name: "Jäst", category: "Skafferi", unit: "st" },
  { name: "Bakpulver", category: "Skafferi", unit: "st" },
  { name: "Vaniljsocker", category: "Skafferi", unit: "st" },
  { name: "Salt", category: "Skafferi", unit: "st" },
  { name: "Svartpeppar", category: "Skafferi", unit: "st" },
  { name: "Krossade tomater", category: "Skafferi", unit: "st" },
  { name: "Passerade tomater", category: "Skafferi", unit: "st" },
  { name: "Tomatpuré", category: "Skafferi", unit: "st" },
  { name: "Kokosmjölk", category: "Skafferi", unit: "st" },
  { name: "Röda linser", category: "Skafferi", unit: "förp" },
  { name: "Kikärtor", category: "Skafferi", unit: "st" },
  { name: "Vita bönor", category: "Skafferi", unit: "st" },
  { name: "Majs", category: "Skafferi", unit: "st" },
  { name: "Olivolja", category: "Skafferi", unit: "l" },
  { name: "Rapsolja", category: "Skafferi", unit: "l" },
  { name: "Ättika", category: "Skafferi", unit: "st" },
  { name: "Soja", category: "Skafferi", unit: "st" },
  { name: "Ketchup", category: "Skafferi", unit: "st" },
  { name: "Senap", category: "Skafferi", unit: "st" },
  { name: "Majonnäs", category: "Skafferi", unit: "st" },
  { name: "Kaffe", category: "Skafferi", unit: "förp" },
  { name: "Te", category: "Skafferi", unit: "förp" },
  { name: "Kakao", category: "Skafferi", unit: "st" },
  { name: "Honung", category: "Skafferi", unit: "st" },
  { name: "Jordgubbssylt", category: "Skafferi", unit: "st" },
  { name: "Jordnötssmör", category: "Skafferi", unit: "st" },
  { name: "Buljongtärningar", category: "Skafferi", unit: "förp" },
  { name: "Pastasås", category: "Skafferi", unit: "st" },
  { name: "Tacokrydda", category: "Skafferi", unit: "st" },
  { name: "Tacoskal", category: "Skafferi", unit: "förp" },

  // ── Fryst ──
  { name: "Frysta ärtor", category: "Fryst", unit: "förp" },
  { name: "Fryst broccoli", category: "Fryst", unit: "förp" },
  { name: "Frysta bär", category: "Fryst", unit: "förp" },
  { name: "Fryst spenat", category: "Fryst", unit: "förp" },
  { name: "Glass", category: "Fryst", unit: "förp" },
  { name: "Fryst pizza", category: "Fryst", unit: "st" },
  { name: "Fiskpinnar", category: "Fryst", unit: "förp" },
  { name: "Fiskgratäng", category: "Fryst", unit: "förp" },
  { name: "Pommes frites", category: "Fryst", unit: "förp" },
  { name: "Köttbullar", category: "Fryst", unit: "förp" },

  // ── Dryck ──
  { name: "Mineralvatten", category: "Dryck", unit: "förp" },
  { name: "Läsk", category: "Dryck", unit: "l" },
  { name: "Apelsinjuice", category: "Dryck", unit: "l" },
  { name: "Äppeljuice", category: "Dryck", unit: "l" },
  { name: "Saft", category: "Dryck", unit: "l" },
  { name: "Öl", category: "Dryck", unit: "förp" },
  { name: "Alkoholfri öl", category: "Dryck", unit: "förp" },
  { name: "Måltidsdryck", category: "Dryck", unit: "l" },
  { name: "Iskaffe", category: "Dryck", unit: "st" },

  // ── Godis & Snacks ──
  { name: "Chips", category: "Godis & Snacks", unit: "förp" },
  { name: "Ostbågar", category: "Godis & Snacks", unit: "förp" },
  { name: "Salta pinnar", category: "Godis & Snacks", unit: "förp" },
  { name: "Popcorn", category: "Godis & Snacks", unit: "förp" },
  { name: "Chokladkaka", category: "Godis & Snacks", unit: "st" },
  { name: "Lördagsgodis", category: "Godis & Snacks", unit: "förp" },
  { name: "Kex", category: "Godis & Snacks", unit: "förp" },
  { name: "Digestivekex", category: "Godis & Snacks", unit: "förp" },

  // ── Hushåll ──
  { name: "Toalettpapper", category: "Hushåll", unit: "förp" },
  { name: "Hushållspapper", category: "Hushåll", unit: "förp" },
  { name: "Diskmedel", category: "Hushåll", unit: "st" },
  { name: "Maskindisktabletter", category: "Hushåll", unit: "förp" },
  { name: "Tvättmedel", category: "Hushåll", unit: "förp" },
  { name: "Sköljmedel", category: "Hushåll", unit: "st" },
  { name: "Allrengöring", category: "Hushåll", unit: "st" },
  { name: "Soppåsar", category: "Hushåll", unit: "förp" },
  { name: "Fryspåsar", category: "Hushåll", unit: "förp" },
  { name: "Bakplåtspapper", category: "Hushåll", unit: "st" },
  { name: "Aluminiumfolie", category: "Hushåll", unit: "st" },
  { name: "Plastfolie", category: "Hushåll", unit: "st" },
  { name: "Värmeljus", category: "Hushåll", unit: "förp" },
  { name: "Batterier AA", category: "Hushåll", unit: "förp" },

  // ── Hygien ──
  { name: "Tandkräm", category: "Hygien", unit: "st" },
  { name: "Tandborste", category: "Hygien", unit: "st" },
  { name: "Schampo", category: "Hygien", unit: "st" },
  { name: "Balsam", category: "Hygien", unit: "st" },
  { name: "Duschkräm", category: "Hygien", unit: "st" },
  { name: "Deodorant", category: "Hygien", unit: "st" },
  { name: "Handtvål", category: "Hygien", unit: "st" },
  { name: "Rakhyvlar", category: "Hygien", unit: "förp" },
  { name: "Bomullspads", category: "Hygien", unit: "förp" },
  { name: "Plåster", category: "Hygien", unit: "förp" },

  // ── Övrigt ──
  { name: "Snittblommor", category: "Övrigt", unit: "st" },
  { name: "Tuggummi", category: "Övrigt", unit: "förp" },
];
