import { SeedFoodItem } from "./food-data-sv";

export const FOOD_ITEMS: SeedFoodItem[] = [
  // ── Fruits & Vegetables ──
  { name: "Bananas", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Apples", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Oranges", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Lemon", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Lime", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Pears", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Grapes", category: "Fruits & Vegetables", unit: "pkg" },
  { name: "Strawberries", category: "Fruits & Vegetables", unit: "pkg" },
  { name: "Blueberries", category: "Fruits & Vegetables", unit: "pkg" },
  { name: "Raspberries", category: "Fruits & Vegetables", unit: "pkg" },
  { name: "Avocado", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Tomatoes", category: "Fruits & Vegetables", unit: "kg" },
  { name: "Cherry tomatoes", category: "Fruits & Vegetables", unit: "pkg" },
  { name: "Cucumber", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Bell pepper", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Iceberg lettuce", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Arugula", category: "Fruits & Vegetables", unit: "pkg" },
  { name: "Baby spinach", category: "Fruits & Vegetables", unit: "pkg" },
  { name: "Carrots", category: "Fruits & Vegetables", unit: "kg" },
  { name: "Potatoes", category: "Fruits & Vegetables", unit: "kg" },
  { name: "Sweet potatoes", category: "Fruits & Vegetables", unit: "kg" },
  { name: "Yellow onion", category: "Fruits & Vegetables", unit: "kg" },
  { name: "Red onion", category: "Fruits & Vegetables", unit: "kg" },
  { name: "Garlic", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Leek", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Broccoli", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Cauliflower", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Zucchini", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Mushrooms", category: "Fruits & Vegetables", unit: "pkg" },
  { name: "Ginger", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Fresh cilantro", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Fresh basil", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Dill", category: "Fruits & Vegetables", unit: "pcs" },
  { name: "Parsley", category: "Fruits & Vegetables", unit: "pcs" },

  // ── Bread & Bakery ──
  { name: "White bread", category: "Bread & Bakery", unit: "pcs" },
  { name: "Whole wheat bread", category: "Bread & Bakery", unit: "pcs" },
  { name: "Baguette", category: "Bread & Bakery", unit: "pcs" },
  { name: "Crispbread", category: "Bread & Bakery", unit: "pkg" },
  { name: "Tortilla wraps", category: "Bread & Bakery", unit: "pkg" },
  { name: "Pita bread", category: "Bread & Bakery", unit: "pkg" },
  { name: "Hamburger buns", category: "Bread & Bakery", unit: "pkg" },
  { name: "Hot dog buns", category: "Bread & Bakery", unit: "pkg" },
  { name: "Cinnamon rolls", category: "Bread & Bakery", unit: "pkg" },
  { name: "Breadsticks", category: "Bread & Bakery", unit: "pkg" },

  // ── Dairy & Eggs ──
  { name: "Whole milk", category: "Dairy & Eggs", unit: "l" },
  { name: "Low-fat milk", category: "Dairy & Eggs", unit: "l" },
  { name: "Skim milk", category: "Dairy & Eggs", unit: "l" },
  { name: "Oat milk", category: "Dairy & Eggs", unit: "l" },
  { name: "Buttermilk", category: "Dairy & Eggs", unit: "l" },
  { name: "Plain yogurt", category: "Dairy & Eggs", unit: "l" },
  { name: "Vanilla yogurt", category: "Dairy & Eggs", unit: "l" },
  { name: "Heavy cream", category: "Dairy & Eggs", unit: "pkg" },
  { name: "Cooking cream", category: "Dairy & Eggs", unit: "pkg" },
  { name: "Crème fraîche", category: "Dairy & Eggs", unit: "pkg" },
  { name: "Sour cream", category: "Dairy & Eggs", unit: "pkg" },
  { name: "Butter", category: "Dairy & Eggs", unit: "pkg" },
  { name: "Margarine", category: "Dairy & Eggs", unit: "pkg" },
  { name: "Eggs 12-pack", category: "Dairy & Eggs", unit: "pkg" },
  { name: "Cheddar cheese", category: "Dairy & Eggs", unit: "pcs" },
  { name: "Swiss cheese", category: "Dairy & Eggs", unit: "pcs" },
  { name: "Mozzarella", category: "Dairy & Eggs", unit: "pkg" },
  { name: "Feta cheese", category: "Dairy & Eggs", unit: "pkg" },
  { name: "Parmesan", category: "Dairy & Eggs", unit: "pcs" },
  { name: "Cream cheese", category: "Dairy & Eggs", unit: "pkg" },
  { name: "Cottage cheese", category: "Dairy & Eggs", unit: "pkg" },

  // ── Meat & Poultry ──
  { name: "Chicken breast", category: "Meat & Poultry", unit: "kg" },
  { name: "Chicken thighs", category: "Meat & Poultry", unit: "kg" },
  { name: "Whole chicken", category: "Meat & Poultry", unit: "pcs" },
  { name: "Ground beef", category: "Meat & Poultry", unit: "kg" },
  { name: "Ground pork & beef mix", category: "Meat & Poultry", unit: "kg" },
  { name: "Pork tenderloin", category: "Meat & Poultry", unit: "kg" },
  { name: "Pork chops", category: "Meat & Poultry", unit: "kg" },
  { name: "Bologna sausage", category: "Meat & Poultry", unit: "pcs" },
  { name: "Cocktail sausages", category: "Meat & Poultry", unit: "pkg" },
  { name: "Hot dogs", category: "Meat & Poultry", unit: "pkg" },
  { name: "Bacon", category: "Meat & Poultry", unit: "pkg" },
  { name: "Ham slices", category: "Meat & Poultry", unit: "pkg" },
  { name: "Salami", category: "Meat & Poultry", unit: "pkg" },
  { name: "Liver pâté", category: "Meat & Poultry", unit: "pcs" },

  // ── Fish & Seafood ──
  { name: "Salmon fillet", category: "Fish & Seafood", unit: "kg" },
  { name: "Cod fillet", category: "Fish & Seafood", unit: "kg" },
  { name: "Shrimp", category: "Fish & Seafood", unit: "kg" },
  { name: "Smoked salmon", category: "Fish & Seafood", unit: "pkg" },
  { name: "Pickled herring", category: "Fish & Seafood", unit: "pkg" },
  { name: "Fish roe spread", category: "Fish & Seafood", unit: "pcs" },
  { name: "Canned tuna", category: "Fish & Seafood", unit: "pcs" },
  { name: "Mackerel in tomato", category: "Fish & Seafood", unit: "pcs" },

  // ── Pantry ──
  { name: "Spaghetti", category: "Pantry", unit: "pkg" },
  { name: "Penne", category: "Pantry", unit: "pkg" },
  { name: "Macaroni", category: "Pantry", unit: "pkg" },
  { name: "Lasagna sheets", category: "Pantry", unit: "pkg" },
  { name: "Rice", category: "Pantry", unit: "pkg" },
  { name: "Bulgur", category: "Pantry", unit: "pkg" },
  { name: "Couscous", category: "Pantry", unit: "pkg" },
  { name: "Quinoa", category: "Pantry", unit: "pkg" },
  { name: "Rolled oats", category: "Pantry", unit: "pkg" },
  { name: "Muesli", category: "Pantry", unit: "pkg" },
  { name: "Cornflakes", category: "Pantry", unit: "pkg" },
  { name: "All-purpose flour", category: "Pantry", unit: "kg" },
  { name: "Sugar", category: "Pantry", unit: "kg" },
  { name: "Yeast", category: "Pantry", unit: "pcs" },
  { name: "Baking powder", category: "Pantry", unit: "pcs" },
  { name: "Vanilla sugar", category: "Pantry", unit: "pcs" },
  { name: "Salt", category: "Pantry", unit: "pcs" },
  { name: "Black pepper", category: "Pantry", unit: "pcs" },
  { name: "Crushed tomatoes", category: "Pantry", unit: "pcs" },
  { name: "Tomato passata", category: "Pantry", unit: "pcs" },
  { name: "Tomato paste", category: "Pantry", unit: "pcs" },
  { name: "Coconut milk", category: "Pantry", unit: "pcs" },
  { name: "Red lentils", category: "Pantry", unit: "pkg" },
  { name: "Chickpeas", category: "Pantry", unit: "pcs" },
  { name: "White beans", category: "Pantry", unit: "pcs" },
  { name: "Corn", category: "Pantry", unit: "pcs" },
  { name: "Olive oil", category: "Pantry", unit: "l" },
  { name: "Canola oil", category: "Pantry", unit: "l" },
  { name: "Vinegar", category: "Pantry", unit: "pcs" },
  { name: "Soy sauce", category: "Pantry", unit: "pcs" },
  { name: "Ketchup", category: "Pantry", unit: "pcs" },
  { name: "Mustard", category: "Pantry", unit: "pcs" },
  { name: "Mayonnaise", category: "Pantry", unit: "pcs" },
  { name: "Coffee", category: "Pantry", unit: "pkg" },
  { name: "Tea", category: "Pantry", unit: "pkg" },
  { name: "Cocoa", category: "Pantry", unit: "pcs" },
  { name: "Honey", category: "Pantry", unit: "pcs" },
  { name: "Strawberry jam", category: "Pantry", unit: "pcs" },
  { name: "Peanut butter", category: "Pantry", unit: "pcs" },
  { name: "Bouillon cubes", category: "Pantry", unit: "pkg" },
  { name: "Pasta sauce", category: "Pantry", unit: "pcs" },
  { name: "Taco seasoning", category: "Pantry", unit: "pcs" },
  { name: "Taco shells", category: "Pantry", unit: "pkg" },

  // ── Frozen ──
  { name: "Frozen peas", category: "Frozen", unit: "pkg" },
  { name: "Frozen broccoli", category: "Frozen", unit: "pkg" },
  { name: "Frozen berries", category: "Frozen", unit: "pkg" },
  { name: "Frozen spinach", category: "Frozen", unit: "pkg" },
  { name: "Ice cream", category: "Frozen", unit: "pkg" },
  { name: "Frozen pizza", category: "Frozen", unit: "pcs" },
  { name: "Fish sticks", category: "Frozen", unit: "pkg" },
  { name: "Fish casserole", category: "Frozen", unit: "pkg" },
  { name: "French fries", category: "Frozen", unit: "pkg" },
  { name: "Meatballs", category: "Frozen", unit: "pkg" },

  // ── Beverages ──
  { name: "Sparkling water", category: "Beverages", unit: "pkg" },
  { name: "Soda", category: "Beverages", unit: "l" },
  { name: "Orange juice", category: "Beverages", unit: "l" },
  { name: "Apple juice", category: "Beverages", unit: "l" },
  { name: "Fruit squash", category: "Beverages", unit: "l" },
  { name: "Beer", category: "Beverages", unit: "pkg" },
  { name: "Non-alcoholic beer", category: "Beverages", unit: "pkg" },
  { name: "Meal drink", category: "Beverages", unit: "l" },
  { name: "Iced coffee", category: "Beverages", unit: "pcs" },

  // ── Candy & Snacks ──
  { name: "Potato chips", category: "Candy & Snacks", unit: "pkg" },
  { name: "Cheese puffs", category: "Candy & Snacks", unit: "pkg" },
  { name: "Pretzels", category: "Candy & Snacks", unit: "pkg" },
  { name: "Popcorn", category: "Candy & Snacks", unit: "pkg" },
  { name: "Chocolate bar", category: "Candy & Snacks", unit: "pcs" },
  { name: "Pick & mix candy", category: "Candy & Snacks", unit: "pkg" },
  { name: "Cookies", category: "Candy & Snacks", unit: "pkg" },
  { name: "Digestive biscuits", category: "Candy & Snacks", unit: "pkg" },

  // ── Household ──
  { name: "Toilet paper", category: "Household", unit: "pkg" },
  { name: "Paper towels", category: "Household", unit: "pkg" },
  { name: "Dish soap", category: "Household", unit: "pcs" },
  { name: "Dishwasher tablets", category: "Household", unit: "pkg" },
  { name: "Laundry detergent", category: "Household", unit: "pkg" },
  { name: "Fabric softener", category: "Household", unit: "pcs" },
  { name: "All-purpose cleaner", category: "Household", unit: "pcs" },
  { name: "Trash bags", category: "Household", unit: "pkg" },
  { name: "Freezer bags", category: "Household", unit: "pkg" },
  { name: "Parchment paper", category: "Household", unit: "pcs" },
  { name: "Aluminum foil", category: "Household", unit: "pcs" },
  { name: "Plastic wrap", category: "Household", unit: "pcs" },
  { name: "Tea lights", category: "Household", unit: "pkg" },
  { name: "AA batteries", category: "Household", unit: "pkg" },

  // ── Hygiene ──
  { name: "Toothpaste", category: "Hygiene", unit: "pcs" },
  { name: "Toothbrush", category: "Hygiene", unit: "pcs" },
  { name: "Shampoo", category: "Hygiene", unit: "pcs" },
  { name: "Conditioner", category: "Hygiene", unit: "pcs" },
  { name: "Shower gel", category: "Hygiene", unit: "pcs" },
  { name: "Deodorant", category: "Hygiene", unit: "pcs" },
  { name: "Hand soap", category: "Hygiene", unit: "pcs" },
  { name: "Razors", category: "Hygiene", unit: "pkg" },
  { name: "Cotton pads", category: "Hygiene", unit: "pkg" },
  { name: "Band-aids", category: "Hygiene", unit: "pkg" },

  // ── Other ──
  { name: "Cut flowers", category: "Other", unit: "pcs" },
  { name: "Chewing gum", category: "Other", unit: "pkg" },
];
