import { app, HttpRequest, HttpResponseInit, InvocationContext } from "@azure/functions";
import { verifyRequest } from "../auth.js";
import { getTableClient } from "../tableClient.js";
import { generateCode } from "../codeGen.js";
import { GenerateCodeResponse } from "../types/shared.js";

export async function generateCodeHandler(
  request: HttpRequest,
  context: InvocationContext
): Promise<HttpResponseInit> {
  const auth = await verifyRequest(request, context);
  if (!auth.authenticated) {
    return { status: 401, jsonBody: { error: "Unauthorized" } };
  }

  try {
    const client = getTableClient("DeviceAuth");
    const code = generateCode();

    await client.createEntity({
      partitionKey: "code",
      rowKey: code,
      status: "active",
    });

    context.log(`Activation code generated by device ${auth.deviceId}`);

    const body: GenerateCodeResponse = { code };
    return { status: 200, jsonBody: body };
  } catch (error: any) {
    context.error("Error generating code:", error);
    return {
      status: 500,
      jsonBody: { error: "Internal server error" },
    };
  }
}

app.http("generateCode", {
  methods: ["POST"],
  authLevel: "anonymous",
  handler: generateCodeHandler,
});
